### ISSUE TITLE
Can't extract the video from the bag

### ISSUE THREAD

**Issue by Hierom** [mlaiacker/rosbag2video#4]
```Traceback (most recent call last):
  File "./rosbag2video.py", line 136, in <module>
    p_avconv[topic] = subprocess.Popen(['avconv','-r',str(opt_fps),'-an','-c','mjpeg','-f','mjpeg','-i','-',out_file],stdin=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Can you help me to fix it?
Thanks

**Comment by mlaiacker** [comment]
avconv is needed and can be installed on Ubuntu with:

sudo apt install libav-tools

**Comment by Hierom** [comment]
Thanks a lot @mlaiacker .
